robot_cfg:
  name: ur10e_hand_right
  urdf_path: ur10e/ur10e_with_right_dexrobot_hand.urdf 

  dof_num: 26

  right_arm_indices: [0, 1, 2, 3, 4, 5]  # Indices for right arm joints: positions 1 to 6 for UR10 arm joints
  right_arm_init: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  ee_type: "hand"
  right_ee: flange
  right_ee_indices: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

  hand_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  human_hand_indices: []
  hand_low_pass_alpha: 0.8
  wrist_low_pass_alpha: 0.5

  arm:  # Configuration for arm inverse kinematics (IK) parameters
    dt: 1e-1  # Time step for IK velocity integration
    eps: 1e-4  # Convergence threshold for IK error
    damp: 1e-12  # Damping factor for IK regularization
    out_lp_alpha: 0.5  # Alpha value for low-pass filter on output

  ee:  # Configuration for end-effector
    right_ee:  # Right end-effector settings
      ckpt_tag: geort_dexhand
      low_pass_alpha: 0.5