robot_cfg:
  name: xarm7_ability_right
  urdf_path: xarm7_ability/xarm7_ability_right_hand.urdf

  dof_num: 17

  right_arm_indices: [0, 1, 2, 3, 4, 5, 6]
  right_arm_init: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  ee_type: hand
  right_ee: ace

  right_ee_indices: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
  hand_indices: [2, 3, 4, 5, 8, 9, 6, 7, 0, 1]

  # for human input data
  human_hand_indices: []
  hand_low_pass_alpha: 0.8
  wrist_low_pass_alpha: 0.5

  arm:
    dt:  1e-1
    eps: 1e-4
    damp: 1e-12
    out_lp_alpha: 0.5

  ee:
    right_ee:
      low_pass_alpha: 0.5