robot_cfg:
  name: h1_inspire

  is_ACE: True

  mode: normal

  pos_scale: 1.5
  roll_scale: 2.0
  pitch_scale: 2.0
  yaw_scale: 2.0

  roll_limit: [-3, 3]
  pitch_limit: [-3, 3]
  yaw_limit: [-3, 3]

  roll_offset: 20

  left_wrist:
    # Note: the end effector frame may look weird, and be different in the 2 arms, check your urdf!
    # e.g., the x axis of the left arm EE points to inside of the flange, while the x axis of the right arm EE points to outside of the flange
    left_wrist_init_rot: [0, 0, 0] # Euler angles (x->y->z) of the end effector (specified in robot config) in the coordinate frame of the first link
    left_wrist_init_pos: [-0.320, 0.1, 0.145] # Position of the end effector in the coordinate frame of the first link
    left_center: [-0.33, 0.05, 0.45]
    left_radius: 0.5 # Center and radius of the constraint sphere, any position out of the sphere will be clipped

  right_wrist:
    right_wrist_init_rot: [0, 0, 0]
    right_wrist_init_pos: [0.320, 0.1, 0.145]
    right_center: [0.33, 0.05, 0.45]
    right_radius: 0.5

  left_agent:
    dynamixel_cfg:
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8J0QI3-if00-port0
      urdf: left_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 0
      hand_type: Left

  right_agent:
    dynamixel_cfg:
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT8ISG7I-if00-port0
      urdf: right_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 2
      hand_type: Right




