robot_cfg:
  name: xarm_ability_right

  is_ACE: True

  mode: normal

  pos_scale: 1.5
  roll_scale: 1.0
  pitch_scale: 1.0
  yaw_scale: 1.0

  roll_limit: [-3, 3]
  pitch_limit: [-3, 3]
  yaw_limit: [-3, 3]

  roll_offset: 0

  right_wrist:
    right_wrist_init_rot: [0, 0, 1.57]
    right_wrist_init_pos: [0.2, 0.2, 0.5]
    right_center: [0.2, 0.2, 0.5]
    right_radius: 10000.0

  right_agent:
    dynamixel_cfg:
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTA9DPE9-if00-port0
      urdf: right_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 3
      hand_type: Right